# Generated by Django 2.0.5 on 2018-07-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umauma_happy_app', '0003_entirefactoraggregate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='date',
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
