# Generated by Django 2.0.5 on 2018-07-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umauma_happy_app', '0004_auto_20180725_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='entirefactoraggregate',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entirefactoraggregate',
            name='percentage',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='entirefactoraggregate',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
