# Generated by Django 2.0.5 on 2018-07-30 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('umauma_happy_app', '0004_auto_20180725_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='entirefactoraggregate',
            name='percentage',
            field=models.DecimalField(decimal_places=5, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='entirefactoraggregate',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='umauma_happy_app.Race'),
        ),
    ]
