# Generated by Django 2.0.5 on 2018-08-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umauma_happy_app', '0006_auto_20180731_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entirefactoraggregate',
            name='hit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entirefactoraggregate',
            name='use',
            field=models.IntegerField(null=True),
        ),
    ]
