from umauma_happy_app.models.course import Course
from umauma_happy_app.models.data import Data
from umauma_happy_app.models.distance_suitability import DistanceSuitability
from umauma_happy_app.models.factor import Factor
from umauma_happy_app.models.favorite import Favorite
from umauma_happy_app.models.ground_condition import GroundCondition
from umauma_happy_app.models.history import History
from umauma_happy_app.models.horse import Horse
from umauma_happy_app.models.jockey import Jockey
from umauma_happy_app.models.leg_quality import LegQuality
from umauma_happy_app.models.race import Race
from umauma_happy_app.models.stable import Stable
from umauma_happy_app.models.trainer import Trainer
from umauma_happy_app.models.user import User
from umauma_happy_app.models.weight import Weight
from umauma_happy_app.models.entire_factor_aggregate import EntireFactorAggregate